import 'dart:io';

import 'package:path/path.dart' as p;

import '../generators/generator.dart';
import '../models/index.dart';
import '../utils.dart';

class AssetsGenerator extends Generator {
  final GeneratorConfig config;
  final String formatterVersion;
  String? _lastGenerated;

  AssetsGenerator({required this.config, required this.formatterVersion});

  @override
  void init() {
    process(config.dir);
  }

  @override
  bool shouldRun(WatchEvent event) => event.path.startsWith(config.dir!);

  @override
  bool isLastGenerated(String path) => path == _lastGenerated;

  @override
  void resetLastGenerated() => _lastGenerated = null;

  @override
  void process(String? path) {
    log('Assets: ${config.dir} ');

    final assetsDir = Directory(config.dir!);
    if (!assetsDir.existsSync()) {
      logln('assets directory not found');
      return;
    }

    final outFilePath = config.outputFile ?? 'lib/constants/assets.dart';
    final assetPathsByDir = _collectAssetPaths(assetsDir);
    final assetCount = assetPathsByDir.values.fold<int>(
      0,
      (count, paths) => count + paths.length,
    );

    if (assetCount == 0) return;

    final output = formatCode(_buildOutput(assetPathsByDir), formatterVersion);
    File(outFilePath).parent.createSync(recursive: true);

    if (fileWriteString(outFilePath, output)) {
      logDone();
    } else {
      logNoChange();
    }

    _lastGenerated = outFilePath;
  }

  Map<String, List<String>> _collectAssetPaths(Directory assetsDir) {
    final assetPathsByDir = <String, List<String>>{};
    final excludeDirs = config.excludeDirs.toSet();

    final directories = assetsDir
        .listSync()
        .whereType<Directory>()
        .where((dir) => !excludeDirs.contains(p.basename(dir.path)))
        .toList()
      ..sort((a, b) => p.basename(a.path).compareTo(p.basename(b.path)));

    for (final dir in directories) {
      final dirName = p.basename(dir.path);
      final assetPaths = dir
          .listSync(recursive: true)
          .whereType<File>()
          .where((file) => !p.basename(file.path).startsWith('.'))
          .map((file) => p.relative(file.path))
          .toList()
        ..sort();

      assetPathsByDir[dirName] = assetPaths;
    }

    return assetPathsByDir;
  }

  String _buildOutput(Map<String, List<String>> assetPathsByDir) {
    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
      ..writeln('// Generated by dartgenerate assets generator')
      ..writeln()
      ..writeln('/// Asset paths for the application.')
      ..writeln('/// Generated from files in the ${config.dir}/ directory.')
      ..writeln('class Assets {')
      ..writeln('  Assets._();')
      ..writeln();

    for (final entry in assetPathsByDir.entries) {
      if (entry.value.isEmpty) continue;

      buffer
        ..writeln('  // ${entry.key.toUpperCase()}')
        ..writeln();

      for (final assetPath in entry.value) {
        final constantName = _generateConstantName(entry.key, assetPath);
        final literal = _toSingleQuotedStringLiteral(assetPath);
        buffer
          ..writeln('  /// $assetPath')
          ..writeln("  static const String $constantName = '$literal';")
          ..writeln();
      }
    }

    buffer.writeln('}');
    return buffer.toString();
  }

  String _generateConstantName(String dirName, String assetPath) {
    final pathWithoutExtension = p.withoutExtension(assetPath);
    final relativePath = p.relative(pathWithoutExtension, from: config.dir);
    final parts =
        p.split(relativePath).where((part) => part != dirName).toList();
    final words = [dirName, ...parts];
    return _toIdentifier(words);
  }

  String _toIdentifier(List<String> parts) {
    final words = parts
        .expand(
          (part) => part
              .replaceAll(RegExp(r'[_\-\s]+'), ' ')
              .replaceAll(RegExp(r'[^a-zA-Z0-9\s]'), '')
              .split(' '),
        )
        .where((word) => word.isNotEmpty)
        .toList();

    if (words.isEmpty) return 'asset';

    final identifier = words.first.toLowerCase() +
        words.skip(1).map((word) {
          final lower = word.toLowerCase();
          return lower.substring(0, 1).toUpperCase() + lower.substring(1);
        }).join();

    if (RegExp(r'^[0-9]').hasMatch(identifier)) {
      return 'asset${identifier.substring(0, 1).toUpperCase()}${identifier.substring(1)}';
    }

    return identifier;
  }

  String _toSingleQuotedStringLiteral(String value) {
    return value
        .replaceAll(r'\', r'\\')
        .replaceAll(r'$', r'\$')
        .replaceAll("'", r"\'");
  }
}
